In [1]:
from brainhack.pulses import Tukey
from brainhack.sequence import Sequence, Modulation
from brainhack.system import System
from brainhack.simulator import Simulate

import matplotlib.pyplot as plt
import numpy as np

In [2]:
pulse = Tukey(
    duration = 0.001, 
    shape = 0.3, 
    flipAngle = 200, 
    offset = 7000
)

sequence = Sequence(
    modulation = Modulation.BP, 
    pulse = pulse, 
    N_pulsePerOffset = 1, 
    N_pulse = 4, 
    N_burst = 10, 
    N_adc = 80, 
    dt_interPulse = 0.0015,
    TR_burst = 0.1, 
    dt_lastBurst = 0.001, 
    ES = 0.006, 
    TR = 3, 
    readout_flipAngle = 5
)

system = System(
    M0a = 1, 
    M0b = 0.1, 
    T1f = 1, 
    T1b = 1, 
    T1D = 0.01, 
    T2f = 0.1, 
    T2b = 1e-5, 
    R = 10
)

system.RFabsorption_Matrix(pulse)

MT0, MTs, *MTds = Simulate(system, sequence)

evol_MTsat_dual_ALT
[[ 2.85305458e-01  1.28176955e-01  3.86943783e+02  5.33094529e-01]
 [ 1.20621788e-02  5.41914082e-03  1.63594335e+01  2.36530660e-02]
 [-9.03889471e-08 -4.06087333e-08 -1.22590630e-04 -1.80061256e-07]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
matmul(evol_MTsat_dual_ALT, evol_RAGE)
[[ 2.50650163e-02  2.66336446e-02  2.68680484e-89  7.92082849e-01]
 [ 1.05970231e-03  1.12602100e-03  1.13594292e-90  3.46026108e-02]
 [-7.94096756e-09 -8.43793218e-09 -8.51227265e-96 -2.62112583e-07]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
v_MTd_ALT
[ 8.87155779e-07  3.87231799e-08 -1.00000000e+00  1.09065342e-06]
MTd_ALT
[ 8.13416769e-01  3.55045693e-02 -9.16881554e+05  1.00000000e+00]


In [3]:
# print(MT0)
# print(MTs)
# for MTd in MTds:
#     print(MTd)

In [4]:
from scipy.linalg import eig as seig, schur
from numpy.linalg import eig

help(eig)

Help on _ArrayFunctionDispatcher in module numpy.linalg:

eig(a)
    Compute the eigenvalues and right eigenvectors of a square array.

    Parameters
    ----------
    a : (..., M, M) array
        Matrices for which the eigenvalues and right eigenvectors will
        be computed

    Returns
    -------
    A namedtuple with the following attributes:

    eigenvalues : (..., M) array
        The eigenvalues, each repeated according to its multiplicity.
        The eigenvalues are not necessarily ordered. The resulting
        array will be of complex type, unless the imaginary part is
        zero in which case it will be cast to a real type. When `a`
        is real the resulting eigenvalues will be real (0 imaginary
        part) or occur in conjugate pairs

    eigenvectors : (..., M, M) array
        The normalized (unit "length") eigenvectors, such that the
        column ``eigenvectors[:,i]`` is the eigenvector corresponding to the
        eigenvalue ``eigenvalues[i]``.

    R

In [5]:
help(schur)

Help on function schur in module scipy.linalg._decomp_schur:

schur(a, output='real', lwork=None, overwrite_a=False, sort=None, check_finite=True)
    Compute Schur decomposition of a matrix.

    The Schur decomposition is::

        A = Z T Z^H

    where Z is unitary and T is either upper-triangular, or for real
    Schur decomposition (output='real'), quasi-upper triangular. In
    the quasi-triangular form, 2x2 blocks describing complex-valued
    eigenvalue pairs may extrude from the diagonal.

    Parameters
    ----------
    a : (M, M) array_like
        Matrix to decompose
    output : {'real', 'complex'}, optional
        When the dtype of `a` is real, this specifies whether to compute
        the real or complex Schur decomposition.
        When the dtype of `a` is complex, this argument is ignored, and the
        complex Schur decomposition is computed.
    lwork : int, optional
        Work array size. If None or -1, it is automatically computed.
    overwrite_a : bool, 

In [6]:
display(schur([[ 2.50650163e-02,  2.66336446e-02,  2.68680484e-89,  7.92082849e-01],
 [ 1.05970231e-03,  1.12602100e-03,  1.13594292e-90,  3.46026108e-02],
 [-7.94096756e-09, -8.43793218e-09, -8.51227265e-96, -2.62112583e-07],
 [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])[0])

print("COMPLETE")

array([[ 2.61910373e-02, -2.55739423e-02, -2.78292343e-07,
         7.92837524e-01],
       [ 0.00000000e+00,  4.88841396e-13,  5.47797248e-18,
        -1.11382489e-03],
       [ 0.00000000e+00,  0.00000000e+00, -4.53540508e-29,
        -2.36356933e-08],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])

COMPLETE
